name: Haskell Lint

on:
  pull_request:
    paths:
      - '.github/workflows/hlint.yml'
      - 'src/**/*.hs'
      - 'test/**/*.hs'
jobs:
  hlint:
    runs-on: ubuntu-latest
    env:
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HLINT_ACTION_LOG_LEVEL: debug
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up HLint
        uses: rwe/actions-hlint-setup@v1

      - name: Haskell Lint
        uses: rwe/actions-hlint-run@v2
        with:
          path: '["src/"]'
          fail-on: warning
      
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':haskell: *Lint check*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}